const ShopActionTypes = {
    // UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS'
    FETCH_COLLECTIIONS_START: 'FETCH_COLLECTIIONS_START',
    FETCH_COLLECTIIONS_SUCCESS: 'FETCH_COLLECTIIONS_SUCCESS',
    FETCH_COLLECTIIONS_FAILURE: 'FETCH_COLLECTIIONS_FAILURE'
}
export default ShopActionTypes